project_id = "duxbzpsezdhvhprwjwmk"

[auth]
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false
double_confirm_changes = true

[functions.generate-kit-from-docs]
verify_jwt = true

[functions.generate-receipt-pdf]
verify_jwt = true

[functions.send-sms]
verify_jwt = true

[functions.migrate-article-covers]
verify_jwt = true

[functions.bulk-create-products]
verify_jwt = false
